import { IMAGES } from "./images";

const MENTORS = [
  {
    id: 1,
    name: "John Doe",
    title: "Web Developer",
    rating: 4.5,
    gender: "Male",
    current_workplace: "Microsoft",
    years_of_experience: "10 years",
    image: IMAGES.user1,
    profileCompletionRate: 80,
    charges: "$ 50",
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Nigeria",
    country_of_residence: "UK",
    certifications: [
      {
        title: "Certification 1",
        issued_by: "Institute of certtification",
        date: "Feb 2022",
        link: "certification.com",
        skills_acquired: "Project Management, Agile"
      },
      {
        title: "Certification 2",
        issued_by: "Institute of certtification",
        date: "Mar 2024",
        link: "certification.com",
        skills_acquired: "Microsoft Azure 2020"
      },
      {
        title: "Certification 3",
        issued_by: "Institute of certtification",
        date: "Oct 2022",
        link: "certification.com",
        skills_acquired: "Web Development"
      },
      {
        title: "Certification 4",
        issued_by: "Institute of certtification",
        date: "Dec 2022",
        link: "certification.com",
        skills_acquired: "Emotional Intelligence in Workplace"
      },
      
    ],
    qualifications: [
      {institution: "combaitore univeristy",
      type_of_qualification: "Doctor of Philosophy",
      area_of_qualification: "Computer Science",
      start_date: "Feb 2014",
      finish_date: "Nov 2018"
      },
      {institution: "combaitore univeristy",
      type_of_qualification: "B.Sc",
      area_of_qualification: "Computer Science",
      start_date: "Feb 2014",
      finish_date: "Nov 2018"
      },     
    ],
    mentoring_fields: [
      "web/software development",
      "programming",
      "IT solutions",
    ],
    work_experience: [{
      company: "Microsoft",
      start_date: "Oct 2018",
      end_date: "Present",
      duration: "6 years",
      job_title: "software developer",
      location: "Remote",
    },
    {
      company: "Right Mentors",
      start_date: "Oct 2021",
      end_date: "Present",
      duration: "3 years",
      job_title: "Founder",
      location: "Lagos, Nigeria",
    },
  
  ],
    communication_platforms: ['Call', 'email', 'physical', 'social media', 'online platforms (audio)', 'online platforms (video)' ],
    recommendations: [
      {
        title: "recommendation 1",
        fullname: "Professor Apalara",
        profession: "Tenured Professor",
        workplace: "King Fahd Unviersity, Saudi Arabia",
        consent: "Yes",
      },
      {
        title: "recommendation 2",
        fullname: "Mark Zuckerbarg",
        profession: "CEO",
        workplace: "Facebook",
        consent: "Yes",
      },
    ],
    appointments: 33,
    totalEarned: 500000,
    field: "Digital Marketing",
    stars: 4,
    no_of_rating: 17,
    country: "Nigeria",
    no_of_feedback: "17",
    location: "Nigeria",
    bookings: 500,
    path: "mentor-1",
    type: "mentor",
    uri: "mentors/mentor-1",
  },
  {
    id: 2,
    name: "John Doe",
    title: "Web Developer",
    gender: "Male",
    rating: 4.5,
    image: IMAGES.user2,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Ghana",
    appointments: 33,
    totalEarned: 500000,
    field: "Data Analysis",
    stars: 4,
    no_of_rating: 17,
    country: "Ghana",
    no_of_feedback: "17",
    location: "Ghana",
    bookings: 1000,
    path: "mentor-2",
    type: "mentor",
    uri: "mentors/mentor-2",
  },
  {
    id: 3,
    name: "John Doe",
    title: "Web Developer",
    gender: "Male",
    rating: 4.5,
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "China",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-3",
    type: "mentor",
    uri: "mentors/mentor-3",
  },
  {
    id: 4,
    name: "John Doe",
    title: "Web Developer",
    gender: "Female",
    rating: 4.5,
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Russia",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-4",
    type: "mentor",
    uri: "mentors/mentor-4",
  },
  {
    id: 5,
    name: "Taofeek Lawal",
    title: "Web Developer",
    gender: "Male",
    rating: 4.5,
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Angola",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-5",
    type: "mentor",
    uri: "mentors/mentor-5",
  },
  {
    id: 6,
    name: "John Doe",
    title: "Web Developer",
    rating: 4.5,
    gender: "Male",
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Algeria",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-6",
    type: "mentor",
    uri: "mentors/mentor-6",
  },
  {
    id: 7,
    name: "Abdullah Adeoba",
    title: "Web Developer",
    rating: 4.5,
    gender: "Male",
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Botswana",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-7",
    type: "mentor",
    uri: "mentors/mentor-7",
  },
  {
    id: 8,
    name: "John Doe",
    title: "Web Developer",
    rating: 4.5,
    gender: "Female",
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Nigeria",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-8",
    type: "mentor",
    uri: "mentors/mentor-8",
  },
  {
    id: 9,
    name: "John Doe",
    title: "Web Developer",
    rating: 4.5,
    image: IMAGES.user3,
    profileCompletionRate: 80,
    mentees: {
      total: 10,
      active: 5,
      completed: 5,
    },
    country_of_origin: "Nigeria",
    appointments: 33,
    totalEarned: 500000,
    field: "Computer Programming",
    stars: 4,
    no_of_rating: 17,
    country: "South Africa",
    no_of_feedback: "17",
    location: "South Africa",
    bookings: 500,
    path: "mentor-9",
    type: "mentor",
    uri: "mentors/mentor-9",
  },
];

export { MENTORS };
